# Generated by Django 2.2.4 on 2019-12-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('roll', models.IntegerField(default=0)),
                ('regno', models.IntegerField(default=0)),
                ('pec', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cno1', models.CharField(max_length=10)),
                ('cname1', models.CharField(max_length=100)),
                ('cno2', models.CharField(max_length=10)),
                ('cname2', models.CharField(max_length=100)),
                ('cno3', models.CharField(max_length=10)),
                ('cname3', models.CharField(max_length=100)),
                ('cno4', models.CharField(max_length=10)),
                ('cname4', models.CharField(max_length=100)),
                ('cno5', models.CharField(max_length=10)),
                ('cname5', models.CharField(max_length=100)),
            ],
        ),
    ]
