# Generated by Django 2.2.3 on 2019-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_courseregister2'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregister',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
