# Generated by Django 2.2.3 on 2019-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semresult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
