# Generated by Django 2.2.3 on 2019-12-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='days',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('classes', models.IntegerField(blank=True, max_length=10)),
            ],
        ),
    ]
