# Generated by Django 2.2.3 on 2019-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='classes',
            field=models.IntegerField(blank=True),
        ),
    ]
